name: Java CI

on:
     push:
       branches: [ main ]
     pull_request:
       branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Download ChromeDriver and give Gradle permission
        run: chmod +x ./gradlew

      - name: Start SUT
        run: java -jar ./artifacts/app-card-delivery.jar &
      
      - name: Wait for server to start
        run: sleep 10

      - name: Run tests
        run: ./gradlew test --info -Dselenide.headless=true 
